Fix error because of cyclic imports
This should fix the error:
$ python autogen.py 
Traceback (most recent call last):
  File "autogen.py", line 11, in <module>
    from header import ForwardHeaderGenerator
  File "/path/KDSoap-master/autogen/header.py", line 6, in <module>
    import autogen
  File "/path/KDSoap-master/autogen/autogen.py", line 11, in <module>
    from header import ForwardHeaderGenerator
ImportError: cannot import name ForwardHeaderGenerator
Please verify this edit and apply it to your repository if it solves that problem.