Prepend "undef daylight" and "undef timezone" to all generated files.
This is to fix compilation errors in wsdl files that use those names,
like groupwise.wsdl -- due to nasty Windows macros.

wsdl_groupwise.h(7040): error C2528: '__daylight': pointer to reference is illegal