Add missing fwd decls for the args used in server methods.
Found in the encapsecurity/authstateless.wsdl testcase, which gave
wsdl_authstateless.h:1505:82: error: ‘__ContextResponseType’ does not name a type